default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: libby_development

test:
  <<: *default
  database: libby_test

production:
  <<: *default
  database: libby_production
  username: libby
  password: <%= ENV["LIBBY_DATABASE_PASSWORD"] %>
